name: CI

on: [push]

jobs:
  phpcs:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        php: [7.3]
    steps:
      - uses: actions/checkout@v1
      - name: Install Composer dependencies
        run: composer install --prefer-dist
      - name: Lint code
        run: php${{ matrix.php }} ./vendor/bin/parallel-lint --exclude tests/app --exclude vendor --exclude bin .
      - name: Check code style
        run: php${{ matrix.php }} ./vendor/bin/phpcs --standard=./ruleset.xml --extensions=php
